---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
platforms:
  - name: kind
    image: bsycorp/kind:v1.17.1
    command: /entrypoint.sh /usr/bin/supervisord --nodaemon -c /etc/supervisord.conf
    privileged: True
    published_ports:
    - 2375:2375
    - 8443:8443
    - 10080:10080
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
